title: My LaTeX Blog
email: djinn@example.com
description: >-
  A Jekyll blog with MathJax and tables.
baseurl: "/my-latex-blog" # â† this must match your repository name
url: "https://djinn-art.github.io"

# theme: minima
plugins:
  - jekyll-feed
